export { default as Home } from './Home'
export { default as About } from './AboutMe'
export { default as ProjetosGit } from './ProjetosGit'
export { default as Projetos } from './Projetos'
export { default as Contato } from './Contato'